name: 'Factorio Mod Portal Publish'
author: 'Shane Madden (OG) & Michael Jess (variable workdir & 2.0.0 mod API update)'
description: 'Publishes repos with Factorio mods to the Factorio mod portal'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'settings'  
  color: 'orange'
inputs:
  path:
    description: 'Path to mod source folder'
    default: '.'
  mod_api_key:
    description: 'Mod portal upload API key. See https://wiki.factorio.com/Mod_upload_API'
    required: true
