name: 'Factorio Mod Portal Publish'
author: 'Shane Madden'
description: 'Publishes repos with Factorio mods to the Factorio mod portal'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'settings'  
  color: 'orange'
inputs:
  path:
    description: 'Path to mod source folder'
    default: '.'
  factorio_user:
    description: 'Factorio mod portal user name'
    required: true
  factorio_password:
    description: 'Factorio mod portal password'
    required: true
